src/objects/Audio__c.object
<CustomObject>
    <fields>
        <fullName>Media__c</fullName>
        <label>Media</label>
        <referenceTo>Media__c</referenceTo>
        <relationshipLabel>Audio</relationshipLabel>
        <relationshipName>Audio</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Audio</label>
    <nameField>
        <label>Audio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audio</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Image__c.object
<CustomObject>
    <fields>
        <fullName>Media__c</fullName>
        <label>Media</label>
        <referenceTo>Media__c</referenceTo>
        <relationshipLabel>Images</relationshipLabel>
        <relationshipName>Images</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Media__c.object
<CustomObject>
    <fields>
        <fullName>Media_Type__c</fullName>
        <label>Media Type</label>
        <picklist>
            <picklistValues>
                <fullName>Image</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Audio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIdeo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Media</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Video__c.object
<CustomObject>
    <fields>
        <fullName>Media__c</fullName>
        <label>Media</label>
        <referenceTo>Media__c</referenceTo>
        <relationshipLabel>Video</relationshipLabel>
        <relationshipName>Video</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Video</label>
    <nameField>
        <label>Video Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Video</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MediaEditController.cls
public with sharing class MediaEditController {
    private final Media__c media;
    private Audio__c audio;
    private Image__c image;
    private Video__c video;

    public MediaEditController(ApexPages.StandardController controller) {
        this.media = (Media__c)controller.getRecord();

        if (this.media.media_type__c == null)
            this.media.media_type__c = 'Image';

        if (this.media.media_type__c == 'Audio')
            this.audio = new Audio__c(Media__c = this.media.Id);
        else if (this.media.media_type__c == 'Image')
            this.image = new Image__c(Media__c = this.media.Id);
        else if (this.media.media_type__c == 'Video')
            this.video = new Video__c(Media__c = this.media.Id);

    }

    public PageReference selectMediaType() {
        this.audio = null;
        this.image = null;
        this.video = null;
        
        if (this.media.media_type__c == 'Audio')
            this.audio = new Audio__c(Media__c = this.media.Id);
        else if (this.media.media_type__c == 'Image')
            this.image = new Image__c(Media__c = this.media.Id);
        else if (this.media.media_type__c == 'Video')
            this.video = new Video__c(Media__c = this.media.Id);

        return null;
    }
    
    public Audio__c getAudio() {
        return this.audio;
    }
    
    public Video__c getVideo() {
        return this.video;
    }
    
    public Image__c getImage() {
        return this.image;
    }
    
    public PageReference save() {
        media.Name = 'Media name';
        insert media;
    
        if (this.media.media_type__c == 'Audio') {
            this.audio.Media__c = this.media.Id;
            insert this.audio;
        } else if (this.media.media_type__c == 'Image') {
            this.image.Media__c = this.media.Id;
            insert this.image;
        } else if (this.media.media_type__c == 'Video') {
            this.video.Media__c = this.media.Id;
            insert this.video;
        }
        
        PageReference mPage = new ApexPages.StandardController(media).view();

        mPage.setRedirect(true);

        return mPage;
    }

}